# Generated by Django 3.2.6 on 2021-08-17 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Baslik')),
                ('content', models.TextField(verbose_name='Icerik')),
                ('created_data', models.DateTimeField(
                    auto_now_add=True, verbose_name='Olusturma tarixi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
    ]
